variables:
  LC_ALL: C

stages:
  - image
  - test

build_image:
  stage: image
  image: docker:git
  services:
  - docker:dind
  before_script:
    - docker info
  script:
    - cd CI
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.nic.cz
    - docker build -t registry.nic.cz/turris/python-ubus/python3-only .
    - docker push registry.nic.cz/turris/python-ubus/python3-only:latest
  tags:
    - dind
  only:
    - CI

test_with_python3:
  stage: test
  image: registry.nic.cz/turris/python-ubus/python3-only
  script:
    - export LD_LIBRARY_PATH=:/usr/local/lib
    - python setup.py test
